import './globals.css';

import localFont from 'next/font/local';

import type { Metadata } from 'next';

const Lalezar = localFont({
	src: './fonts/Lalezar-Regular.ttf',
	display: 'swap',
	variable: '--font-lalezar',
});

export const metadata: Metadata = {
	title: 'ALDY SERVICES',
	description: 'Generated by Aldy Tech',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fa">
			<body className={`${Lalezar.className} antialiased m-0`}>{children}</body>
		</html>
	);
}
